### ISSUE TITLE
Getting started: A clean skeleton

### ISSUE THREAD

**Issue by gburnett** [nesterow/frontless#69]
I try to create a frontless app with a [clean skeleton](https://frontless.js.org/en/start.html).  The application does not run.

1. `$ npx create-frontless myapp --clean`
2. `$ cd myapp`
3. `$ yarn start`

**Expected behavior**
The application should not crash.  I am guessing that a near empty app should launch.

**Actual behaviour**
I see the following output in my terminal:
```
$ yarn start
yarn run v1.17.3
$ cross-env NODE_ENV=development gulp
[21:48:55] Using gulpfile ~/lrn/myapp/gulpfile.js
[21:48:55] Starting 'default'...
DEV: development bus is started on ::8998
DEV: waiting for building events
[21:48:55] Finished 'default' after 151 ms
[21:48:55] running tasks...
[21:48:56] Using gulpfile ~/lrn/myapp/gulpfile.js
[21:48:56] Starting 'worker'...
[21:48:56] Starting 'boot'...
[21:48:56] Starting 'scss'...
[21:48:58] Finished 'boot' after 2.3 s
[21:48:58] Finished 'scss' after 2.32 s
[21:48:59] Finished 'worker' after 2.34 s
DEV: status -> building
DEV: status -> frontend
DEV: status -> finished
DEV: status -> started
[21:48:59] [nodemon] 1.19.1
[21:48:59] [nodemon] to restart at any time, enter `rs`
[21:48:59] [nodemon] watching: *.*
[21:48:59] [nodemon] starting `node index.js ./config/environ.env`
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'examples/chat.riot'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/gburnett/lrn/myapp/pages/examples/chat.riot:8:36)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Module._compile (/home/gburnett/lrn/myapp/node_modules/pirates/lib/index.js:99:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Object.newLoader [as .riot] (/home/gburnett/lrn/myapp/node_modules/pirates/lib/index.js:104:7)
    at Module.load (internal/modules/cjs/loader.js:653:32)
[21:49:03] [nodemon] app crashed - waiting for file changes before starting...
```

**Environment:**
 - OS: Arch linux
 - node: v10.16.0
 - yarn: v1.17.3

**Comment by nesterow** [comment]
Thanks for reporting it. The command works as expected now.
